special_chars:
  link_char: '∟'
  style_char: '∫'

remove_data_different_style_from_headers: false



# Any rightmost/leftmost column from the following list will be dropped from the table.
drop_columns_blacklist:
  - "Notes"
  - "Reference"
  - "References"
  - "Ref"
  - "Ref."
  - "Note"
  - "Notes"
  - "Remarks"
  - "Remarks/Notes"
  - "Remarks/Note"
  - "Remarks/Ref."
  - "Reference/Note"
  - "No."

# Any cell with the following values will be considered NULL.
null_chars:
  - "—"
  - "-"
  - "none"
  - "–"

# Whether to drop the table if the program finds a column to be removed. (Not including the columns in the `drop_columns_blacklist` list)
drop_table_on_column_removal: true

# Maximum number of NULL values allowed in a single row.
# If a row has more than this number of NULL values, it will be considered invalid and will be dropped.
# Example: A row with 3 NULL values will be considered invalid if this value is set to 2.
maximum_row_null_values:
  type: percent # Can be 'abs' or 'percent'
  value: 0.8 # 3 NULL values in a row.

# Maximum number of NULL values allowed in a single column.
# If a column has more than this number of NULL values, it will be considered invalid and will be dropped.
maximum_column_null_values:
  type: percent # Can be 'abs' or 'percent'
  value: 0.4 # 40% of number of cells in the column.


# If the last row of the table is an aggregation row, it will be dropped.
# This is useful for tables where the last row is a summary or total row.
last_row_agg_mechanism: true

# Whether to allow non-ASCII characters in the table.
only_ascii_chars: true
  

# Known date formats for parsing and storing the original date values.
known_dates_format:
  - "%d %b"      # 7 May
  - "%d %B"      # 7 January (full month)
  - "%d/%m/%Y"   # 07/05/2025
  - "%Y-%m-%d"   # 2025-05-07
  - "%b %d %Y"  # May 7 2025
  - "%d-%m-%Y"   # 07-05-2025
  - "%m/%d/%Y"   # 05/07/2025
  - "%d %b %Y"  # 7 May 2025
  - "%b %Y"  # May 2025
  - "%B %Y"  # June 2025
  - "%B %d %Y"  # June 7 2025
  - "%B %d"  # June 7
  - "%b %d"  # June 7
  - "%d %b %Y"  # 7 May 2025
  - "%d %B %Y"  # 7 May 2025


# Minimum table size for a table to be considered valid.
minimum_table_size:
  rows: 8
  columns: 2


header_manipulations:
  # Example: https://en.wikipedia.org/wiki/List_of_cities_in_Yamanashi_Prefecture_by_population - Rank (2020) -> Rank
  remove_data_inside_parentheses: false
  # Example: https://en.wikipedia.org/wiki/Latin_American_migration_to_the_United_Kingdom#Official_statistics_on_Latin_American-born_residents - Population (2021/22 census)[14][15][16] -> Population (2021/22 census)
  remove_data_inside_square_brackets: true

cell_manipulations:
  # Example: https://en.wikipedia.org/wiki/2009%E2%80%9310_Biathlon_World_Cup_%E2%80%93_Sprint_Men#Standings - Name column (Emil Hegle Svendsen (NOR) -> Emil Hegle Svendsen)
  remove_data_inside_parentheses: true
  remove_data_inside_square_brackets: true

maximum_mixed_types:
  # Maximum number of mixed types allowed in a single column.
  # If a column has more than this number of mixed types, it will be considered invalid and will be dropped.
  # Example: A column with both numbers and strings will be considered invalid if this value is set to 1.
  type: abs # Can be 'abs' or 'percent'
  value: 3 # 10% of number of cells in the table.
  # Example for 'abs':
  # type: abs
  # value: 2 # 2 cells in the table.

